# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/xiaomi/mione_plus/setup-makefiles.sh

# Linkable audio blobs are declared in Android.mk.
PRODUCT_PACKAGES += libaudioalsa libacdbloader libacdbmapper libnv liboncrpc

# Other prebuilt libraries needed during linking
PRODUCT_COPY_FILES += \
	vendor/xiaomi/mione_plus/proprietary/vendor/lib/libv8.so:obj/lib/libv8.so

PRODUCT_COPY_FILES += \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libaudioparsers.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudioparsers.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libv8.so:$(TARGET_COPY_OUT_VENDOR)/lib/libv8.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/hw/sensors.vendor.msm8660.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensors.vendor.msm8660.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/egl/eglsubAndroid.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/eglsubAndroid.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/egl/libEGL_adreno200.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libEGL_adreno200.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/egl/libGLESv1_CM_adreno200.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_adreno200.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/egl/libGLESv2_adreno200.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_adreno200.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/egl/libGLESv2S3D_adreno200.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2S3D_adreno200.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/egl/libplayback_adreno200.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libplayback_adreno200.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/egl/libq3dtools_adreno200.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libq3dtools_adreno200.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libC2D2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libC2D2.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libc2d2_z180.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2d2_z180.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libOpenVG.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOpenVG.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libOpenCL.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOpenCL.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libllvm-arm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-arm.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libgsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgsl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libsc-a2xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsc-a2xx.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/a225_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225_pfp.fw \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/a225_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225_pm4.fw \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/a225p5_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225p5_pm4.fw \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/yamato_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/yamato_pfp.fw \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/yamato_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/yamato_pm4.fw \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/dsps_fluid.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/dsps_fluid.mdt \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/dsps_fluid.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/dsps_fluid.b03 \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/dsps_fluid.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/dsps_fluid.b02 \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/dsps_fluid.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/dsps_fluid.b01 \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/dsps_fluid.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/dsps_fluid.b00 \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/fw_bcm4329.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_bcm4329.bin \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/fw_bcm4329_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_bcm4329_apsta.bin \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/fw_bcmdhd.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_bcmdhd.bin \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/fw_bcmdhd_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_bcmdhd_apsta.bin \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/fw_bcmdhd_p2p.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_bcmdhd_p2p.bin \
  vendor/xiaomi/mione_plus/proprietary/vendor/etc/wifi/bcmdhd.cal:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd.cal \
  vendor/xiaomi/mione_plus/proprietary/vendor/etc/wifi/nvram.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram.txt \
  vendor/xiaomi/mione_plus/proprietary/vendor/etc/init.qcom.modem_links.sh:$(TARGET_COPY_OUT_VENDOR)/etc/init.qcom.modem_links.sh \
  vendor/xiaomi/mione_plus/proprietary/vendor/etc/init.qcom.post_fs.sh:$(TARGET_COPY_OUT_VENDOR)/etc/init.qcom.post_fs.sh \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/qmiproxy:$(TARGET_COPY_OUT_VENDOR)/bin/qmiproxy \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsutils.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libidl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmiservices.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/netmgrd:$(TARGET_COPY_OUT_VENDOR)/bin/netmgrd \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnetmgr.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libdsi_netctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsi_netctrl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdi.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libqdp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdp.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qc-qmi-1.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qcril-hook-oem.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libqc-opt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqc-opt.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/mm-qcamera-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/mm-qcamera-daemon \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/v4l2-qcamera-app:$(TARGET_COPY_OUT_VENDOR)/bin/v4l2-qcamera-app \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/liboemcamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcamera.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libgemini.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgemini.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmipl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmipl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmjpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmjpeg.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmmpo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmmpo.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmstereo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmstereo.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmmpod.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmmpod.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmrtpdecoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmrtpdecoder.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmjps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmjps.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmm-color-convertor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-color-convertor.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libimage-omx-common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimage-omx-common.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libimage-jpeg-enc-omx-comp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimage-jpeg-enc-omx-comp.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libimage-jpeg-dec-omx-comp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimage-jpeg-dec-omx-comp.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmcamera_faceproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_faceproc.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmcamera_frameproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_frameproc.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmcamera_hdr_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_hdr_lib.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmcamera_image_stab.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_image_stab.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmcamera_statsproc31.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_statsproc31.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_wavelet_lib.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmstillomx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmstillomx.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/gpsone_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/gpsone_daemon \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libgpsone_bit_api.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgpsone_bit_api.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/thermald:$(TARGET_COPY_OUT_VENDOR)/bin/thermald \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libthermal_mitigation_fusion.so:$(TARGET_COPY_OUT_VENDOR)/lib/libthermal_mitigation_fusion.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libthermal_mitigation.so:$(TARGET_COPY_OUT_VENDOR)/lib/libthermal_mitigation.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/cnd:$(TARGET_COPY_OUT_VENDOR)/bin/cnd \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libcneqmiutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcneqmiutils.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libcneutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcneutils.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libxml.so:$(TARGET_COPY_OUT_VENDOR)/lib/libxml.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/mm-pp-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/mm-pp-daemon \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmm-abl-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-abl-oem.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmm-abl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-abl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/port-bridge:$(TARGET_COPY_OUT_VENDOR)/bin/port-bridge \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/bridgemgrd:$(TARGET_COPY_OUT_VENDOR)/bin/bridgemgrd \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/qmuxd:$(TARGET_COPY_OUT_VENDOR)/bin/qmuxd \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/rmt_storage:$(TARGET_COPY_OUT_VENDOR)/bin/rmt_storage \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/usbhub:$(TARGET_COPY_OUT_VENDOR)/bin/usbhub \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/usbhub_init:$(TARGET_COPY_OUT_VENDOR)/bin/usbhub_init \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx074_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx074_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx074_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx074_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx074_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx074_video_hd.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx074_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx074_zsl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx091_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx091_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx091_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx091_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx091_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx091_video_hd.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx105_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx105_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx105_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx105_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx105_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx105_zsl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx105p_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx105p_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx105p_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx105p_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx105p_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx105p_zsl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx105s_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx105s_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx105s_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx105s_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx105s_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx105s_zsl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx132_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx132_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx132_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx132_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx132_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx132_zsl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_mt9e0132_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mt9e0132_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_mt9e0132_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mt9e0132_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_mt9e0133_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mt9e0133_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_mt9e0133_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mt9e0133_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_mt9e0134_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mt9e0134_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_mt9e0134_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mt9e0134_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_mt9e013_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mt9e013_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_mt9e013_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mt9e013_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_mt9e013_video_hfr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mt9e013_video_hfr.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov2720_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov2720_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov2720_hfr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov2720_hfr.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov2720_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov2720_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov2720_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov2720_zsl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov5647_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5647_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov5647_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5647_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov5647_video_hfr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5647_video_hfr.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov8825_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8825_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov8825_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8825_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov9726_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov9726_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov9726_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov9726_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3h2_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h2_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3h2_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h2_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3h2_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h2_zsl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3h2s_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h2s_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3h2s_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h2s_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3h2s_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h2s_zsl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3l1yx_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l1yx_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3l1yx_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l1yx_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3l1yx_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l1yx_video_hd.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3l1yx_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l1yx_zsl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k4e1_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4e1_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k4e1_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4e1_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/usr/keylayout/8660_handset.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/8660_handset.kl \
  vendor/xiaomi/mione_plus/proprietary/vendor/usr/keylayout/cyttsp-i2c.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/cyttsp-i2c.kl \
  vendor/xiaomi/mione_plus/proprietary/vendor/usr/keylayout/ffa-keypad.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/ffa-keypad.kl \
  vendor/xiaomi/mione_plus/proprietary/vendor/usr/keylayout/fluid-keypad.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/fluid-keypad.kl \
  vendor/xiaomi/mione_plus/proprietary/vendor/usr/keylayout/mione-keypad.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/mione-keypad.kl \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmparser.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmparser.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmosal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmosal.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libDivxDrm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libDivxDrm.so \
