# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/xiaomi/mione_plus/setup-makefiles.sh

# Linkable audio blobs are declared in Android.mk.
PRODUCT_PACKAGES += libaudioalsa libacdbloader libacdbmapper

# Other prebuilt libraries needed during linking
PRODUCT_COPY_FILES += \
	vendor/xiaomi/mione_plus/proprietary/vendor/lib/libv8.so:obj/lib/libv8.so

PRODUCT_COPY_FILES += \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libaudioparsers.so:system/vendor/lib/libaudioparsers.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libv8.so:system/vendor/lib/libv8.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/hw/sensors.vendor.msm8660.so:system/vendor/lib/hw/sensors.vendor.msm8660.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/egl/libEGL_adreno200.so:system/vendor/lib/egl/libEGL_adreno200.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/egl/libGLESv1_CM_adreno200.so:system/vendor/lib/egl/libGLESv1_CM_adreno200.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/egl/libGLESv2_adreno200.so:system/vendor/lib/egl/libGLESv2_adreno200.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/egl/libGLESv2S3D_adreno200.so:system/vendor/lib/egl/libGLESv2S3D_adreno200.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/egl/libplayback_adreno200.so:system/vendor/lib/egl/libplayback_adreno200.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/egl/libq3dtools_adreno200.so:system/vendor/lib/egl/libq3dtools_adreno200.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libc2d2_z180.so:system/vendor/lib/libc2d2_z180.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libOpenVG.so:system/vendor/lib/libOpenVG.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libllvm-arm.so:system/vendor/lib/libllvm-arm.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/a225_pfp.fw:system/vendor/firmware/a225_pfp.fw \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/a225_pm4.fw:system/vendor/firmware/a225_pm4.fw \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/a225p5_pm4.fw:system/vendor/firmware/a225p5_pm4.fw \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/yamato_pfp.fw:system/vendor/firmware/yamato_pfp.fw \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/yamato_pm4.fw:system/vendor/firmware/yamato_pm4.fw \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/dsps_fluid.mdt:system/vendor/firmware/dsps_fluid.mdt \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/dsps_fluid.b03:system/vendor/firmware/dsps_fluid.b03 \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/dsps_fluid.b02:system/vendor/firmware/dsps_fluid.b02 \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/dsps_fluid.b01:system/vendor/firmware/dsps_fluid.b01 \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/dsps_fluid.b00:system/vendor/firmware/dsps_fluid.b00 \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/fw_bcm4329.bin:system/vendor/firmware/fw_bcm4329.bin \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/fw_bcm4329_apsta.bin:system/vendor/firmware/fw_bcm4329_apsta.bin \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/fw_bcmdhd.bin:system/vendor/firmware/fw_bcmdhd.bin \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/fw_bcmdhd_apsta.bin:system/vendor/firmware/fw_bcmdhd_apsta.bin \
  vendor/xiaomi/mione_plus/proprietary/vendor/firmware/fw_bcmdhd_p2p.bin:system/vendor/firmware/fw_bcmdhd_p2p.bin \
  vendor/xiaomi/mione_plus/proprietary/vendor/etc/wifi/bcmdhd.cal:system/vendor/etc/wifi/bcmdhd.cal \
  vendor/xiaomi/mione_plus/proprietary/vendor/etc/wifi/nvram.txt:system/vendor/etc/wifi/nvram.txt \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libnv.so:system/vendor/lib/libnv.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/etc/init.qcom.modem_links.sh:system/vendor/etc/init.qcom.modem_links.sh \
  vendor/xiaomi/mione_plus/proprietary/vendor/etc/init.qcom.post_fs.sh:system/vendor/etc/init.qcom.post_fs.sh \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libdsm.so:system/vendor/lib/libdsm.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/liboncrpc.so:system/vendor/lib/liboncrpc.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libqueue.so:system/vendor/lib/libqueue.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/qmiproxy:system/vendor/bin/qmiproxy \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/netmgrd:system/vendor/bin/netmgrd \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/mm-qcamera-daemon:system/vendor/bin/mm-qcamera-daemon \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/v4l2-qcamera-app:system/vendor/bin/v4l2-qcamera-app \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libgemini.so:system/vendor/lib/libgemini.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmmpo.so:system/vendor/lib/libmmmpo.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmstereo.so:system/vendor/lib/libmmstereo.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmmpod.so:system/vendor/lib/libmmmpod.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmrtpdecoder.so:system/vendor/lib/libmmrtpdecoder.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmjps.so:system/vendor/lib/libmmjps.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libimage-omx-common.so:system/vendor/lib/libimage-omx-common.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libimage-jpeg-enc-omx-comp.so:system/vendor/lib/libimage-jpeg-enc-omx-comp.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libimage-jpeg-dec-omx-comp.so:system/vendor/lib/libimage-jpeg-dec-omx-comp.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmcamera_frameproc.so:system/vendor/lib/libmmcamera_frameproc.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmcamera_image_stab.so:system/vendor/lib/libmmcamera_image_stab.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmcamera_statsproc31.so:system/vendor/lib/libmmcamera_statsproc31.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmstillomx.so:system/vendor/lib/libmmstillomx.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/gpsone_daemon:system/vendor/bin/gpsone_daemon \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libgpsone_bit_api.so:system/vendor/lib/libgpsone_bit_api.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/thermald:system/vendor/bin/thermald \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libthermal_mitigation_fusion.so:system/vendor/lib/libthermal_mitigation_fusion.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libthermal_mitigation.so:system/vendor/lib/libthermal_mitigation.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/cnd:system/vendor/bin/cnd \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libcneutils.so:system/vendor/lib/libcneutils.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/mm-pp-daemon:system/vendor/bin/mm-pp-daemon \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/port-bridge:system/vendor/bin/port-bridge \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/bridgemgrd:system/vendor/bin/bridgemgrd \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/qmuxd:system/vendor/bin/qmuxd \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/rmt_storage:system/vendor/bin/rmt_storage \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/usbhub:system/vendor/bin/usbhub \
  vendor/xiaomi/mione_plus/proprietary/vendor/bin/usbhub_init:system/vendor/bin/usbhub_init \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx074_default_video.so:system/vendor/lib/libchromatix_imx074_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx074_preview.so:system/vendor/lib/libchromatix_imx074_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx074_video_hd.so:system/vendor/lib/libchromatix_imx074_video_hd.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx074_zsl.so:system/vendor/lib/libchromatix_imx074_zsl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx091_default_video.so:system/vendor/lib/libchromatix_imx091_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx091_preview.so:system/vendor/lib/libchromatix_imx091_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx091_video_hd.so:system/vendor/lib/libchromatix_imx091_video_hd.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx105_default_video.so:system/vendor/lib/libchromatix_imx105_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx105_preview.so:system/vendor/lib/libchromatix_imx105_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx105_zsl.so:system/vendor/lib/libchromatix_imx105_zsl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx105p_default_video.so:system/vendor/lib/libchromatix_imx105p_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx105p_preview.so:system/vendor/lib/libchromatix_imx105p_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx105p_zsl.so:system/vendor/lib/libchromatix_imx105p_zsl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx105s_default_video.so:system/vendor/lib/libchromatix_imx105s_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx105s_preview.so:system/vendor/lib/libchromatix_imx105s_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx105s_zsl.so:system/vendor/lib/libchromatix_imx105s_zsl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx132_default_video.so:system/vendor/lib/libchromatix_imx132_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx132_preview.so:system/vendor/lib/libchromatix_imx132_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_imx132_zsl.so:system/vendor/lib/libchromatix_imx132_zsl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_mt9e0132_default_video.so:system/vendor/lib/libchromatix_mt9e0132_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_mt9e0132_preview.so:system/vendor/lib/libchromatix_mt9e0132_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_mt9e0133_default_video.so:system/vendor/lib/libchromatix_mt9e0133_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_mt9e0133_preview.so:system/vendor/lib/libchromatix_mt9e0133_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_mt9e0134_default_video.so:system/vendor/lib/libchromatix_mt9e0134_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_mt9e0134_preview.so:system/vendor/lib/libchromatix_mt9e0134_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_mt9e013_default_video.so:system/vendor/lib/libchromatix_mt9e013_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_mt9e013_preview.so:system/vendor/lib/libchromatix_mt9e013_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_mt9e013_video_hfr.so:system/vendor/lib/libchromatix_mt9e013_video_hfr.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov2720_default_video.so:system/vendor/lib/libchromatix_ov2720_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov2720_hfr.so:system/vendor/lib/libchromatix_ov2720_hfr.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov2720_preview.so:system/vendor/lib/libchromatix_ov2720_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov2720_zsl.so:system/vendor/lib/libchromatix_ov2720_zsl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov5647_default_video.so:system/vendor/lib/libchromatix_ov5647_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov5647_preview.so:system/vendor/lib/libchromatix_ov5647_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov5647_video_hfr.so:system/vendor/lib/libchromatix_ov5647_video_hfr.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov8825_default_video.so:system/vendor/lib/libchromatix_ov8825_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov8825_preview.so:system/vendor/lib/libchromatix_ov8825_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov9726_default_video.so:system/vendor/lib/libchromatix_ov9726_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_ov9726_preview.so:system/vendor/lib/libchromatix_ov9726_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3h2_default_video.so:system/vendor/lib/libchromatix_s5k3h2_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3h2_preview.so:system/vendor/lib/libchromatix_s5k3h2_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3h2_zsl.so:system/vendor/lib/libchromatix_s5k3h2_zsl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3h2s_default_video.so:system/vendor/lib/libchromatix_s5k3h2s_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3h2s_preview.so:system/vendor/lib/libchromatix_s5k3h2s_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3h2s_zsl.so:system/vendor/lib/libchromatix_s5k3h2s_zsl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3l1yx_default_video.so:system/vendor/lib/libchromatix_s5k3l1yx_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3l1yx_preview.so:system/vendor/lib/libchromatix_s5k3l1yx_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3l1yx_video_hd.so:system/vendor/lib/libchromatix_s5k3l1yx_video_hd.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k3l1yx_zsl.so:system/vendor/lib/libchromatix_s5k3l1yx_zsl.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k4e1_default_video.so:system/vendor/lib/libchromatix_s5k4e1_default_video.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libchromatix_s5k4e1_preview.so:system/vendor/lib/libchromatix_s5k4e1_preview.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/usr/keylayout/8660_handset.kl:system/vendor/usr/keylayout/8660_handset.kl \
  vendor/xiaomi/mione_plus/proprietary/vendor/usr/keylayout/cyttsp-i2c.kl:system/vendor/usr/keylayout/cyttsp-i2c.kl \
  vendor/xiaomi/mione_plus/proprietary/vendor/usr/keylayout/ffa-keypad.kl:system/vendor/usr/keylayout/ffa-keypad.kl \
  vendor/xiaomi/mione_plus/proprietary/vendor/usr/keylayout/fluid-keypad.kl:system/vendor/usr/keylayout/fluid-keypad.kl \
  vendor/xiaomi/mione_plus/proprietary/vendor/usr/keylayout/mione-keypad.kl:system/vendor/usr/keylayout/mione-keypad.kl \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
  vendor/xiaomi/mione_plus/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
